# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrubber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_a1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_a1', to='scrubber.sentence')),
                ('msg_a2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_a2', to='scrubber.sentence')),
                ('msg_b1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_b1', to='scrubber.sentence')),
                ('msg_b2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_b2', to='scrubber.sentence')),
                ('msg_c1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_c1', to='scrubber.sentence')),
            ],
        ),
    ]
