# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrubber', '0003_auto_20170929_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='mTurk_id',
            field=models.TextField(),
        ),
    ]
