# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrubber', '0004_auto_20170929_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='alteredText',
            new_name='annotatedText',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='scrubbedText',
        ),
        migrations.RemoveField(
            model_name='task',
            name='msg_a1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='msg_a2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='msg_b1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='msg_b2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='msg_c1',
        ),
        migrations.AddField(
            model_name='task',
            name='sentences',
            field=models.TextField(default='[]'),
        ),
    ]
